doctrine:
  dbal:
    driver: '%env(resolve:DATABASE_DRIVER)%'
    server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
    host: '%env(resolve:DATABASE_HOST)%'
    port: '%env(resolve:DATABASE_PORT)%'
    dbname: '%env(resolve:DATABASE_NAME)%'
    user: '%env(resolve:DATABASE_USER)%'
    password: '%env(resolve:DATABASE_PASSWORD)%'
    charset: UTF8
    profiling_collect_backtrace: '%kernel.debug%'
    use_savepoints: true
    types:
      trip_id: App\TravelExpenseTracker\Infrastructure\Doctrine\DBAL\Type\TripIdType
      traveler_id: App\TravelExpenseTracker\Infrastructure\Doctrine\DBAL\Type\TravelerIdType
      expense_id: App\TravelExpenseTracker\Infrastructure\Doctrine\DBAL\Type\ExpenseIdType
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
    auto_mapping: true
    mappings:
      TravelExpenseTracker_Entity:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/TravelExpenseTracker/Infrastructure/Doctrine/ORM/Mapping/Entity'
        prefix: 'App\TravelExpenseTracker\Domain\Entity'
        alias: TravelExpenseTracker_Entity
      TravelExpenseTracker_ValueObject:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/TravelExpenseTracker/Infrastructure/Doctrine/ORM/Mapping/ValueObject'
        prefix: 'App\TravelExpenseTracker\Domain\ValueObject'
        alias: TravelExpenseTracker_ValueObject
    controller_resolver:
      auto_mapping: false

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
