services:
  nginx:
    container_name: ${PROJECT_PREFIX:-tet}-nginx
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT:-8080}:80
    volumes:
      - .:/var/www/travel-expense-tracker
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: ${PROJECT_PREFIX:-tet}-php-fpm
    build: ./docker/php-fpm
    depends_on:
      - postgres
    volumes:
      - .:/var/www/travel-expense-tracker

  postgres:
    container_name: ${PROJECT_PREFIX:-tet}-postgres
    image: postgres:${POSTGRES_VERSION:-15}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
